steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/opsoracle/backend:$COMMIT_SHA
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/opsoracle/backend:latest
      - .
    dir: backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/opsoracle/backend:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - opsoracle-backend
      - --image=asia-south1-docker.pkg.dev/$PROJECT_ID/opsoracle/backend:$COMMIT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/opsoracle/backend:$COMMIT_SHA
  - asia-south1-docker.pkg.dev/$PROJECT_ID/opsoracle/backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
